### ISSUE TITLE
gcc13 installation does not install static libstdc++.a

### ISSUE THREAD

**Issue by nbriggs** [oracle/solaris-userland#18]
While the gcc13 build produces both
```
prototype/sparc/usr/gcc/13/lib/sparcv9/libstdc++.a
prototype/sparc/usr/gcc/13/lib/libstdc++.a
```
the manifest does not install these files.

When attempting to build rust this missing library results in an “Empty search path given via '-L’” error.

**Comment by psumbera** [comment]
This looks like some older problem. You might need to look at to https://github.com/rust-lang/rust/issues/97260.

Generally we don't ship static libraries.

Do you know that we bundle Rust with Solaris?

**Comment by nbriggs** [comment]
Thanks - I had missed one of the places where it depended on the static library, so I had fixed it by installing the static library from the gcc13 build.  I've fixed it properly now in rust 1.62.0.

I have been using a personal/non-commercial Solaris 11.4 system, but as far as I'm aware there hasn't been a Solaris 11.4 CBE release since the original one announced March 2, 2022, so for building open source packages that depend on more modern releases of things like Rust the only option seems to be building from the userland git repository.

It would be a great help if the solaris-userland git repository contained the intermediate versions of Rust, since it appears that you can never move more than one minor version ahead at at time (1.70.0 is definitely not compilable with 1.61.0 which was the previous checked in version).

**Comment by psumbera** [comment]
I do some Rust interim version builds in my personal repo here: https://github.com/psumbera/solaris-userland/commits/master/

**Comment by nbriggs** [comment]
Thanks for that.  I'm sure it will be helpful.

**Comment by vlmarek** [comment]
.
