### ISSUE TITLE
mailman having uid 98 triggers compliance check for system accounts

### ISSUE THREAD

**Issue by JPBI** [oracle/solaris-userland#2]
Not directly an issue but a cross package and registration/reservation thing:
The manifest nails mailman to uid 98 while system ids (less than 100) are checked by a compliance report, which then yields an alarm as it checks against an inline list of 'known' account names:
Command: /usr/lib/compliance/tests/OSC-25505-ids-reserved-uids-sce.sh
Yield: Invalid User with Reserved UID: mailman

Noticed on usr/lib/compliance/tests/OSC-25505-ids-reserved-uids-sce.sh from pkg:/security/compliance/policy-tests@0.5.11-0.175.3.29.0.4.0 and pkg://solaris/mail/mailman@2.1.24.1,5.11-0.175.3.23.0.4.0:20170802T150919Z)
)
I don't know about 'system account' registration policies, especially with regard to foss packages, but at least wanted to ring the bell ;-)

Best regards
Jens

**Comment by JPBI** [comment]
Hi Darren, 
thanks for taking care and providing the pointer/info. If uid assignment to packages is coordinated, then that should be all fine.
Jens

**Comment by vlmarek** [comment]
Based on the info I'm closing this issue.

Thank you
__ 
  Vlad
