### ISSUE TITLE
Typo in solaris-userland/components/net-snmp/Makefile, change 'B' with 'D'

### ISSUE THREAD

**Issue by grueni** [oracle/solaris-userland#5]
MIB_MOBULES.sparc 
should read 
MIB_MODULES.sparc

MIB_MOBULES += $(MIB_MODULES.$(MACH)) 
should read 
MIB_MODULES += $(MIB_MODULES.$(MACH))

**Comment by vlmarek** [comment]
Sorry for the late response, thanks for the catch!

**Comment by vlmarek** [comment]
I have filled internal bug for that, thanks again

**Comment by vlmarek** [comment]
This has been fixed by https://github.com/oracle/solaris-userland/commit/3fed6e3c41d5ce382d28cdad73b1cfa312adbed9#diff-152b1047a6e1fcbdd1ba2f2b30bdcbfb

Cheers
