### ISSUE TITLE
Missing Firefox and Cargo

### ISSUE THREAD

**Issue by Michele31415** [oracle/solaris-userland#6]
What happened to Firefox and Cargo?  They were in components last week (1/4/20) and now (1/12/20) they're gone :-(

**Comment by vlmarek** [comment]
Hmm, I can still see them:
https://github.com/oracle/solaris-userland/tree/master/components/rust
https://github.com/oracle/solaris-userland/tree/master/components/desktop/firefox

**Comment by Michele31415** [comment]
Indeed.  My mistake.  I forgot that firefox was in a subdirectory of desktop and that cargo was under rust.  Never mind :-)  And if you're just browsing components, files and subdirectories look the same.
