### ISSUE TITLE
Clone and Download not working

### ISSUE THREAD

**Issue by hergla** [oracle/solaris-userland#9]
Cloned the Git Repo.
Get a lot of errors during "game download"

hergen@solaris11:~/Source$ git clone https://github.com/oracle/solaris-userland /export/home/hergen/Source/Solaris-userland
Cloning into '/export/home/hergen/Source/Solaris-userland'...
remote: Enumerating objects: 118293, done.
remote: Counting objects: 100% (7177/7177), done.
remote: Compressing objects: 100% (2985/2985), done.
remote: Total 118293 (delta 4304), reused 6572 (delta 3991), pack-reused 111116
Receiving objects: 100% (118293/118293), 160.55 MiB | 4.37 MiB/s, done.
Resolving deltas: 100% (54099/54099), done.
Updating files: 100% (9256/9256), done.
hergen@solaris11:~/Source$ cd Solaris-userland/components/
hergen@solaris11:~/Source/Solaris-userland/components$ gmake download
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
/bin/mkdir -p /export/home/hergen/Source/Solaris-userland/i386
Generating component list...
Generating component dependencies...
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
Generating component list...
Generating component dependencies...
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
/bin/mkdir -p /export/home/hergen/Source/Solaris-userland/i386/logs
download a2ps
make[1]: Entering directory '/export/home/hergen/Source/Solaris-userland/components/a2ps'
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
/usr/php/7.3/bin/php-config: No such file or directory
/usr/php/8.0/bin/php-config: No such file or directory
/export/home/hergen/Source/Solaris-userland/tools/userland-fetch --file a2ps-4.14.tar.gz --url 'https://ftp.gnu.org/gnu/a2ps/a2ps-4.14.tar.gz' --hash 'sha256:f3ae8d3d4564a41b6e2a21f237d2f2b104f48108591e8b83497500182a3ab3a4' --sigurl 'https://ftp.gnu.org/gnu/a2ps/a2ps-4.14.tar.gz.sig' 
Source a2ps-4.14.tar.gz... not found, skipping file copy
Source http://userland.us.oracle.com/source-archives/a2ps-4.14.tar.gz... 
    downloading... failed
Can't open url http://userland.us.oracle.com/source-archives/a2ps-4.14.tar.gz
<urlopen error [Errno 8] node name or service name not known>
Source https://ftp.gnu.org/gnu/a2ps/a2ps-4.14.tar.gz... 
    downloading... 
    validating signature... ok
    validating hash... ok
/usr/bin/touch a2ps-4.14.tar.gz
make[1]: Leaving directory '/export/home/hergen/Source/Solaris-userland/components/a2ps'
download aalib
make[1]: Entering directory '/export/home/hergen/Source/Solaris-userland/components/aalib'
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
/usr/php/7.3/bin/php-config: No such file or directory
/usr/php/8.0/bin/php-config: No such file or directory
/export/home/hergen/Source/Solaris-userland/tools/userland-fetch --file aalib-1.4rc5.tar.gz --url 'http://downloads.sourceforge.net/aa-project/aalib-1.4rc5.tar.gz' --hash 'sha256:fbddda9230cf6ee2a4f5706b4b11e2190ae45f5eda1f0409dc4f99b35e0a70ee'  
Source aalib-1.4rc5.tar.gz... not found, skipping file copy
Source http://userland.us.oracle.com/source-archives/aalib-1.4rc5.tar.gz... 
    downloading... failed
Can't open url http://userland.us.oracle.com/source-archives/aalib-1.4rc5.tar.gz
<urlopen error [Errno 8] node name or service name not known>
Source http://downloads.sourceforge.net/aa-project/aalib-1.4rc5.tar.gz... 
    downloading... 
    validating signature... skipped (no signature URL)
    validating hash... ok
/usr/bin/touch aalib-1.4rc5.tar.gz
make[1]: Leaving directory '/export/home/hergen/Source/Solaris-userland/components/aalib'
download acpidump
make[1]: Entering directory '/export/home/hergen/Source/Solaris-userland/components/acpidump'
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
/bin/bash: /usr/perl5/5.32/bin/perl: No such file or directory
/usr/php/7.3/bin/php-config: No such file or directory
/usr/php/8.0/bin/php-config: No such file or directory
/export/home/hergen/Source/Solaris-userland/tools/userland-fetch --file pmtools-20071116.tar.gz --url 'https://01.org/sites/default/files/page/pmtools-20071116.tar.gz' --hash 'sha256:91751774976e39f6237efd0326eb35196a9346220b92ad35894a33283e872748'  
Source pmtools-20071116.tar.gz... not found, skipping file copy
Source http://userland.us.oracle.com/source-archives/pmtools-20071116.tar.gz... 
    downloading... failed
Can't open url http://userland.us.oracle.com/source-archives/pmtools-20071116.tar.gz
<urlopen error [Errno 8] node name or service name not known>
Source https://01.org/sites/default/files/page/pmtools-20071116.tar.gz... 
    downloading... failed
Can't open url https://01.org/sites/default/files/page/pmtools-20071116.tar.gz
HTTP Error 404: Not Found
Cannot download the archives! Terminating...
make[1]: *** [/export/home/hergen/Source/Solaris-userland/make-rules/prep.mk:39: pmtools-20071116.tar.gz] Error 100
make[1]: Leaving directory '/export/home/hergen/Source/Solaris-userland/components/acpidump'
gmake: *** [Makefile:249: acpidump.nosetup] Error 2
hergen@solaris11:~/Source/Solaris-userland/components$

**Comment by vlmarek** [comment]
No response, I'm closing the bug.
